
version: '3'
services:
  web:
    build: ../my-app
    ports:
      - "4200:4201"
       
    volumes:
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf  

  nginx:
    image: nginx:alpine    
    ports:
      - "80:80"
    depends_on:
      - web