
# Usar la imagen de Node como base
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instalar las dependencias de la aplicación
RUN npm install

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiar el resto de los archivos de la aplicación al directorio de trabajo
COPY . .

# Exponer el puerto 4200 para el servidor de desarrollo de Angular
EXPOSE 4200

# Comando para arrancar el servidor de desarrollo de Angular
CMD ["ng", "serve", "--host", "0.0.0.0"]